# .github/workflows/terraform.yml
name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workspace: [dev, staging, prod]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0

    - name: Select Terraform Workspace
      run: terraform workspace select ${{ matrix.workspace }} || terraform workspace new ${{ matrix.workspace }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var-file=${{ matrix.workspace }}.tfvars -out=tfplan-${{ matrix.workspace }}.out

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && matrix.workspace == 'prod'
      run: terraform apply tfplan-${{ matrix.workspace }}.out
