# .github/workflows/terraform.yml
name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workspace: [dev]

    env:  # Define the AWS environment variables here
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.2

    - name: Terraform Init
      run: terraform init

    - name: Select Terraform Workspace
      run: terraform workspace select ${{ matrix.workspace }} || terraform workspace new ${{ matrix.workspace }}   

    - name: Terraform Plan
      run: terraform plan -var-file=${{ matrix.workspace }}.tfvars -out=tfplan-${{ matrix.workspace }}.out
